title: 学习总结——《Head First HTML 与 CSS》
email: qiang.zhang0314@gmail.com
description: >-
  这是我的个人学习总结，是打造开发技术栈的基础，也是知识的沉淀与归纳。
baseurl: "/learn-head-first-html-and-css"
url: ""
github_username: mrzhqiang

markdown: kramdown
# If you need local preview, just uncomment the line
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

search_enabled: true

aux_links:
  "在 GitHub 上查看":
    - "//github.com/mrzhqiang/learn-head-first-html-and-css"