title: Learn <head first html and css>
email: qiang.zhang0314@gmail.com
description: >-
  这是对《Head First HTML 与 CSS》一书的学习总结。
baseurl: "/learn-head-first-html-and-css"
url: ""
github_username: mrzhqiang

markdown: kramdown

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

search_enabled: true

aux_links:
  "在 GitHub 上查看":
    - "//github.com/mrzhqiang/learn-head-first-html-and-css"