# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 《Head First HTML and CSS》 学习笔记
email: qiang.zhang0314@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  这是我的个人学习笔记系列之一，我希望打造一个全栈技术体系，将热爱的计算机知识归纳和沉淀。
baseurl: "/learn-head-first-html-and-css"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mrzhqiang

# If you need local preview, just uncomment the line
plugins:
  - jekyll-feed

# Aux links for the upper right navigation
aux_links:
  "在 GitHub 上查看":
    - "//github.com/mrzhqiang/learn-head-first-html-and-css"
theme: jekyll-theme-cayman