title: Learn <head first html and css>
email: qiang.zhang0314@gmail.com
description: >-
  这是对《Head First HTML 与 CSS》一书的学习总结。
baseurl: "/learn-head-first-html-and-css"
url: ""
github_username: mrzhqiang

markdown: kramdown
# If you need local preview, just uncomment the line
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

search_enabled: true

aux_links:
  "在 GitHub 上查看":
    - "//github.com/mrzhqiang/learn-head-first-html-and-css"